APP_DEFINES = APP_SSID=YOURSSID \
			  APP_PASS=YOURSSIDPASS \
			  MQTT_SERVER=192.168.1.23 \
			  MQTT_PORT=1883 \
			  SET_TOPIC=/test/set \
			  STATE_TOPIC=/test \
			  COOGLEIOT_ALLOW_INSECURE_SSL \
			  COOGLEIOT_OTA_CHECK_FOR_UPGRADE_ON_INIT \
			  BOOT_BIG_FLASH
